version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx-container
    ports:
      - "80:80"
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana-container
    ports:
      - "3000:3000"
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus-container
    ports:
      - "9090:9090"
    restart: always
